### ISSUE TITLE
Touching an enchanted golden apple crashes

### ISSUE THREAD

**Issue by abm991** [gloridifice/WaterSource#70]
When the inventory is opened, the mouse crashes when it touches the enchanted golden apple
Here's my crash log:
[21:45:43] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.15.11
[21:45:43] [main/INFO]: Loading 78 mods:
	- cloth-config 11.1.118
	   \-- cloth-basic-math 0.6.1
	- fabric-api 0.92.2+1.20.1
	   |-- fabric-api-base 0.4.31+1802ada577
	   |-- fabric-api-lookup-api-v1 1.6.36+1802ada577
	   |-- fabric-biome-api-v1 13.0.13+1802ada577
	   |-- fabric-block-api-v1 1.0.11+1802ada577
	   |-- fabric-block-view-api-v2 1.0.1+1802ada577
	   |-- fabric-blockrenderlayer-v1 1.1.41+1802ada577
	   |-- fabric-client-tags-api-v1 1.1.2+1802ada577
	   |-- fabric-command-api-v1 1.2.34+f71b366f77
	   |-- fabric-command-api-v2 2.2.13+1802ada577
	   |-- fabric-commands-v0 0.2.51+df3654b377
	   |-- fabric-containers-v0 0.1.64+df3654b377
	   |-- fabric-content-registries-v0 4.0.11+1802ada577
	   |-- fabric-convention-tags-v1 1.5.5+1802ada577
	   |-- fabric-crash-report-info-v1 0.2.19+1802ada577
	   |-- fabric-data-attachment-api-v1 1.0.0+de0fd6d177
	   |-- fabric-data-generation-api-v1 12.3.4+1802ada577
	   |-- fabric-dimensions-v1 2.1.54+1802ada577
	   |-- fabric-entity-events-v1 1.6.0+1c78457f77
	   |-- fabric-events-interaction-v0 0.6.2+1802ada577
	   |-- fabric-events-lifecycle-v0 0.2.63+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.40+1802ada577
	   |-- fabric-item-api-v1 2.1.28+1802ada577
	   |-- fabric-item-group-api-v1 4.0.12+1802ada577
	   |-- fabric-key-binding-api-v1 1.0.37+1802ada577
	   |-- fabric-keybindings-v0 0.2.35+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.22+1802ada577
	   |-- fabric-loot-api-v2 1.2.1+1802ada577
	   |-- fabric-loot-tables-v1 1.1.45+9e7660c677
	   |-- fabric-message-api-v1 5.1.9+1802ada577
	   |-- fabric-mining-level-api-v1 2.1.50+1802ada577
	   |-- fabric-model-loading-api-v1 1.0.3+1802ada577
	   |-- fabric-models-v0 0.4.2+9386d8a777
	   |-- fabric-networking-api-v1 1.3.11+1802ada577
	   |-- fabric-networking-v0 0.3.51+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.3+1802ada577
	   |-- fabric-particles-v1 1.1.2+1802ada577
	   |-- fabric-recipe-api-v1 1.0.21+1802ada577
	   |-- fabric-registry-sync-v0 2.3.3+1802ada577
	   |-- fabric-renderer-api-v1 3.2.1+1802ada577
	   |-- fabric-renderer-indigo 1.5.2+85287f9f77
	   |-- fabric-renderer-registries-v1 3.2.46+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.37+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.28+1802ada577
	   |-- fabric-rendering-v0 1.1.49+df3654b377
	   |-- fabric-rendering-v1 3.0.8+1802ada577
	   |-- fabric-resource-conditions-api-v1 2.3.8+1802ada577
	   |-- fabric-resource-loader-v0 0.11.10+1802ada577
	   |-- fabric-screen-api-v1 2.0.8+1802ada577
	   |-- fabric-screen-handler-api-v1 1.3.30+1802ada577
	   |-- fabric-sound-api-v1 1.0.13+1802ada577
	   |-- fabric-transfer-api-v1 3.3.5+8dd72ea377
	   \-- fabric-transitive-access-wideners-v1 4.3.1+1802ada577
	- fabric-language-kotlin 1.11.0+kotlin.2.0.0
	   |-- org_jetbrains_kotlin_kotlin-reflect 2.0.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib 2.0.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 2.0.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 2.0.0
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.24.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.1
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.1
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.6.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.3
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.3
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.3
	- fabricloader 0.15.11
	   \-- mixinextras 0.3.5
	- java 22
	- minecraft 1.20.1
	- modmenu 7.2.2
	- simplefog 1.4.0
	- watersource 2.0.4+1.20.1-fabric-beta
	   |-- com_akuleshov7_ktoml-core-jvm 0.5.1
	   |-- com_akuleshov7_ktoml-file-jvm 0.5.1
	   |-- com_akuleshov7_ktoml-source-jvm 0.5.1
	   \-- com_squareup_okio_okio-jvm 3.1.0
[21:45:44] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/%e5%bb%96%e4%b8%9c%e5%8d%8e/Desktop/.minecraft/libraries/net/fabricmc/sponge-mixin/0.13.3+mixin.0.8.5/sponge-mixin-0.13.3+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[21:45:44] [main/INFO]: Compatibility level set to JAVA_16
[21:45:44] [main/INFO]: Compatibility level set to JAVA_17
[21:45:48] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[21:45:50] [main/WARN]: Invalid registry value type detected for PerfOS counters. Should be REG_DWORD. Ignoring: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\PerfOS\Performance\Disable Performance Counters.
[21:45:59] [Datafixer Bootstrap/INFO]: 188 Datafixer optimizations took 445 milliseconds
[21:46:02] [Render thread/INFO]: [STDERR]: [LWJGL] [ThreadLocalUtil] Unsupported JNI version detected, this may result in a crash. Please inform LWJGL developers.
[21:46:02] [Render thread/INFO]: Environment: authHost='http://localhost:55273/authserver', accountsHost='http://127.0.0.1:55307/https/api.mojang.com', sessionHost='http://127.0.0.1:55307/https/sessionserver.mojang.com', servicesHost='http://127.0.0.1:55307/https/api.minecraftservices.com', name='PROD'
[21:46:02] [Render thread/INFO]: Setting user: abm991
[21:46:04] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
[21:46:04] [Worker-Main-1/INFO]: Checking mod updates...
[21:46:04] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
[21:46:06] [Render thread/INFO]: Reloading ResourceManager: vanilla, fabric (cloth-config, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-containers-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-events-lifecycle-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-tables-v1, fabric-message-api-v1, fabric-mining-level-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-networking-v0, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, modmenu, simplefog, watersource)
[21:46:06] [Worker-Main-3/INFO]: Found unifont_all_no_pua-15.0.06.hex, loading
[21:46:07] [Worker-Main-6/WARN]: Exception loading blockstate definition: 'watersource:blockstates/strainer/natural_strainer.json' missing model for variant: 'watersource:strainer/natural_strainer#'
[21:46:07] [Realms Notification Availability checker #1/INFO]: Could not authorize you against Realms server: Invalid session id
[21:46:07] [Worker-Main-6/WARN]: Exception loading blockstate definition: 'watersource:blockstates/purified_water.json' missing model for variant: 'watersource:purified_water#level=9'
[21:46:07] [Worker-Main-6/WARN]: Exception loading blockstate definition: 'watersource:blockstates/purified_water.json' missing model for variant: 'watersource:purified_water#level=7'
[21:46:07] [Worker-Main-6/WARN]: Exception loading blockstate definition: 'watersource:blockstates/purified_water.json' missing model for variant: 'watersource:purified_water#level=8'
[21:46:07] [Worker-Main-6/WARN]: Exception loading blockstate definition: 'watersource:blockstates/purified_water.json' missing model for variant: 'watersource:purified_water#level=5'
[21:46:07] [Worker-Main-6/WARN]: Exception loading blockstate definition: 'watersource:blockstates/purified_water.json' missing model for variant: 'watersource:purified_water#level=6'
[21:46:07] [Worker-Main-6/WARN]: Exception loading blockstate definition: 'watersource:blockstates/purified_water.json' missing model for variant: 'watersource:purified_water#level=3'
[21:46:07] [Worker-Main-6/WARN]: Exception loading blockstate definition: 'watersource:blockstates/purified_water.json' missing model for variant: 'watersource:purified_water#level=4'
[21:46:07] [Worker-Main-6/WARN]: Exception loading blockstate definition: 'watersource:blockstates/purified_water.json' missing model for variant: 'watersource:purified_water#level=1'
[21:46:07] [Worker-Main-6/WARN]: Exception loading blockstate definition: 'watersource:blockstates/purified_water.json' missing model for variant: 'watersource:purified_water#level=2'
[21:46:07] [Worker-Main-6/WARN]: Exception loading blockstate definition: 'watersource:blockstates/purified_water.json' missing model for variant: 'watersource:purified_water#level=0'
[21:46:07] [Worker-Main-6/WARN]: Exception loading blockstate definition: 'watersource:blockstates/purified_water.json' missing model for variant: 'watersource:purified_water#level=13'
[21:46:07] [Worker-Main-6/WARN]: Exception loading blockstate definition: 'watersource:blockstates/purified_water.json' missing model for variant: 'watersource:purified_water#level=12'
[21:46:07] [Worker-Main-6/WARN]: Exception loading blockstate definition: 'watersource:blockstates/purified_water.json' missing model for variant: 'watersource:purified_water#level=11'
[21:46:07] [Worker-Main-6/WARN]: Exception loading blockstate definition: 'watersource:blockstates/purified_water.json' missing model for variant: 'watersource:purified_water#level=10'
[21:46:07] [Worker-Main-6/WARN]: Exception loading blockstate definition: 'watersource:blockstates/purified_water.json' missing model for variant: 'watersource:purified_water#level=15'
[21:46:07] [Worker-Main-6/WARN]: Exception loading blockstate definition: 'watersource:blockstates/purified_water.json' missing model for variant: 'watersource:purified_water#level=14'
[21:46:08] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[21:46:08] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[21:46:08] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on 扬声器 (Realtek(R) Audio)
[21:46:08] [Render thread/INFO]: Sound engine started
[21:46:08] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[21:46:08] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/signs.png-atlas
[21:46:08] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[21:46:08] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[21:46:08] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/armor_trims.png-atlas
[21:46:08] [Render thread/INFO]: Created: 128x64x4 minecraft:textures/atlas/decorated_pot.png-atlas
[21:46:08] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[21:46:08] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[21:46:08] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[21:46:08] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[21:46:08] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[21:46:08] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[21:46:08] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[21:46:32] [Render thread/WARN]: doggytalents:natto_bite missing from registry, but requested!
[21:46:32] [Render thread/INFO]: [fabric-registry-sync] Loaded registry data [file 1/4]
[21:46:33] [Render thread/INFO]: Loaded 7 recipes
[21:46:33] [Render thread/INFO]: Loaded 1282 advancements
[21:46:33] [Render thread/INFO]: watersource:hydration - Resource count: 16
[21:46:33] [Render thread/INFO]: Successfully load <watersource:hydration> data <minecraft:hydration/dry_item_cookie.json>
[21:46:33] [Render thread/INFO]: Successfully load <watersource:hydration> data <watersource:hydration/fluid_purified_water.json>
[21:46:33] [Render thread/INFO]: Successfully load <watersource:hydration> data <watersource:hydration/fluid_water.json>
[21:46:33] [Render thread/INFO]: Successfully load <watersource:hydration> data <minecraft:hydration/item_apple.json>
[21:46:33] [Render thread/INFO]: Successfully load <watersource:hydration> data <minecraft:hydration/item_beetroot_soup.json>
[21:46:33] [Render thread/INFO]: Successfully load <watersource:hydration> data <minecraft:hydration/item_enchanted_golden_apple.json>
[21:46:33] [Render thread/INFO]: Successfully load <watersource:hydration> data <minecraft:hydration/item_glistering_melon_slice.json>
[21:46:33] [Render thread/INFO]: Successfully load <watersource:hydration> data <minecraft:hydration/item_glow_berries.json>
[21:46:33] [Render thread/INFO]: Successfully load <watersource:hydration> data <minecraft:hydration/item_golden_apple.json>
[21:46:33] [Render thread/INFO]: Successfully load <watersource:hydration> data <minecraft:hydration/item_melon_slice.json>
[21:46:33] [Render thread/INFO]: Successfully load <watersource:hydration> data <minecraft:hydration/item_mushroom_stew.json>
[21:46:33] [Render thread/INFO]: Successfully load <watersource:hydration> data <minecraft:hydration/item_potion_water.json>
[21:46:33] [Render thread/INFO]: Successfully load <watersource:hydration> data <watersource:hydration/item_purified_water_bottle.json>
[21:46:33] [Render thread/INFO]: Successfully load <watersource:hydration> data <minecraft:hydration/item_rabbit_stew.json>
[21:46:33] [Render thread/INFO]: Successfully load <watersource:hydration> data <minecraft:hydration/item_suspicious_stew.json>
[21:46:33] [Render thread/INFO]: Successfully load <watersource:hydration> data <minecraft:hydration/item_sweet_berries.json>
[21:46:33] [Render thread/INFO]: All <watersource:hydration> data loaded. Count: 16.
[21:46:33] [Render thread/INFO]: watersource:filter_recipe - Resource count: 1
[21:46:33] [Render thread/INFO]: Successfully load <watersource:filter_recipe> data <watersource:filter_recipe/water_to_purified_water.json>
[21:46:33] [Render thread/INFO]: All <watersource:filter_recipe> data loaded. Count: 1.
[21:46:34] [Render thread/INFO]: Applied 0 biome modifications to 0 of 64 new biomes in 1.292 ms
[21:46:34] [Server thread/INFO]: Starting integrated minecraft server version 1.20.1
[21:46:34] [Server thread/INFO]: Generating keypair
[21:46:34] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[21:46:36] [Render thread/INFO]: 准备生成区域中：0%
[21:46:36] [Render thread/INFO]: 准备生成区域中：0%
[21:46:36] [Render thread/INFO]: 准备生成区域中：0%
[21:46:36] [Render thread/INFO]: 准备生成区域中：0%
[21:46:36] [Render thread/INFO]: 准备生成区域中：4%
[21:46:37] [Render thread/INFO]: 准备生成区域中：95%
[21:46:37] [Render thread/INFO]: Time elapsed: 2515 ms
[21:46:37] [Server thread/INFO]: Changing view distance to 12, from 10
[21:46:37] [Server thread/INFO]: Changing simulation distance to 12, from 0
[21:46:37] [Server thread/INFO]: abm991[local:E:a591258c] logged in with entity id 55 at (149.81173358971526, -60.0, -212.18954374555236)
[21:46:37] [Server thread/INFO]: abm991加入了游戏
[21:46:38] [Server thread/INFO]: Player <literal{abm991}>'s water level data attached.
[21:46:38] [Server thread/INFO]: Player <literal{abm991}>'s pos offset data attached.
[21:46:38] [Render thread/INFO]: Loaded 78 advancements
[21:46:49] [Server thread/INFO]: Stopping server
[21:46:49] [Server thread/INFO]: Saving players
[21:46:49] [Server thread/INFO]: Saving worlds
[21:46:50] [Server thread/INFO]: Saving chunks for level 'ServerLevel[新的世界]'/minecraft:overworld
[21:46:50] [Server thread/INFO]: Saving chunks for level 'ServerLevel[新的世界]'/minecraft:the_end
[21:46:50] [Server thread/INFO]: Saving chunks for level 'ServerLevel[新的世界]'/minecraft:the_nether
[21:46:50] [Server thread/INFO]: ThreadedAnvilChunkStorage (新的世界 (2)): All chunks are saved
[21:46:50] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[21:46:50] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[21:46:50] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[21:46:51] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Rendering screen
	at net.minecraft.class_757.method_3192(class_757.java:954) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1219) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[1.20.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
Caused by: java.util.UnknownFormatConversionException: Conversion = '.'
	at java.util.Formatter.parse(Formatter.java:2858) ~[?:?]
	at java.util.Formatter.format(Formatter.java:2780) ~[?:?]
	at java.util.Formatter.format(Formatter.java:2734) ~[?:?]
	at java.lang.String.format(String.java:4432) ~[?:?]
	at xyz.koiro.watersource.event.ItemTooltipEventHandlers.drawRestoration(ItemTooltipEventHandlers.kt:147) ~[watersource-2.0.4+1.20.1-fabric-beta.jar:?]
	at xyz.koiro.watersource.event.ItemTooltipEventHandlers.renderItemTooltipHydrationData$lambda$2(ItemTooltipEventHandlers.kt:29) ~[watersource-2.0.4+1.20.1-fabric-beta.jar:?]
	at xyz.koiro.watersource.event.ModClientEvents.DRAW_MOUSEOVER_TOOLTIP$lambda$1$lambda$0(ModClientEvents.kt:19) ~[watersource-2.0.4+1.20.1-fabric-beta.jar:?]
	at net.minecraft.class_465.handler$zlm000$watersource$drawMouseoverTooltip(class_465.java:699) ~[client-intermediary.jar:?]
	at net.minecraft.class_465.method_2380(class_465.java:178) ~[client-intermediary.jar:?]
	at net.minecraft.class_481.method_25394(class_481.java:734) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_47413(class_437.java:110) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:945) ~[client-intermediary.jar:?]
	... 6 more

**Comment by gloridifice** [comment]
Fixed in 2.0.5
